version: '3'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - "8080:80"

  vpodobaika-upload:
    build:
      dockerfile: Dockerfile
      context: ./vpodobaika-upload
    depends_on:
      - nginx
